12 add privmsg command
IRC-WIR/ft_irc pull request #84
Opened 2024-10-27 11:38 UTC by weijuan82113

privmsgのPRです。
チャンネルの送信を確認していない以外は確認済みです、
下記は確認内容とまります。

## テストケース

## 認証
- （OK）ログイン前、動作しない
## エラー
- （OK） ERR_NOSUCHNICK
- （OK）### ERR_CANNOTSENDTOCHAN
- （OK）### ERR_NOTEXTTOSEND
## 成功
- (OK)ユーザー送信確認
- (OK)チャンネル送信確認?

2024-10-31 17:52 UTC, paphio-kitsuki requested changes

2024-10-31 17:52 UTC, paphio-kitsuki commented on src/event_handler.cpp
> +	if (*target.c_str() == '#' && !event.IsChannelEvent()) {
ちょっと分かりにくいので、
```suggestion
	if (target[0] == '#' && !event.IsChannelEvent()) {
```
こんなのはどうでしょうか。
operator[]はconstの場合も対応しているようです。
[リファレンス](https://cpprefjp.github.io/reference/string/basic_string/op_at.html)

2024-10-31 17:52 UTC, paphio-kitsuki commented on src/event_handler.cpp
> +	const std::string& target = event.get_command_params()[0];
この前にまずエラーチェックを行わないと、パラメータが足りない場合にセグフォしますよ。

2024-10-31 17:52 UTC, paphio-kitsuki commented on src/event_handler.cpp
> +void EventHandler::CheckChannelTarget(Event& event) {
この設計では一個目のパラメータの先頭が#で、かつChannelEventになっていないコマンドすべてが対象となってしまいます。
確実にアウトと言える例として、

quit # -> 正常なコマンド
quit -> パラメータがないのでセグフォ

やはり、特定のコマンドにターゲットを絞ったほうが良い気がします。

2024-11-01 01:19 UTC, weijuan82113 commented on src/event_handler.cpp
> +	if (*target.c_str() == '#' && !event.IsChannelEvent()) {
その通りです、その方がわかりやすいですので修正を承認します

2024-11-01 04:28 UTC, weijuan82113 commented on src/event_handler.cpp
> +void EventHandler::CheckChannelTarget(Event& event) {
レビューありがとうございます、
そうですね、
当時チャンネルの設計に関数の役割は自分の中に不明確だったので、
チェンネルへの送信を10/30に図面で認識したとおりに修正したいです。
そのため、一度JOINコマンドを実装したコードをメインにマージしてから、
下記を修正をします、指摘があったらお願いします

・ERR_NOSUCHCHANNELとERR_CANNOTSENDTOCHANが混乱して実装しまった（どちらでも反映する）
・ERR_CANNOTSENDTOCHAN：チャンネルのnモードを確認して、チャンネルの外からの送信を許可するか確認
　→nモードの確認が必要なので、JOINコマンドのコードを取り入れて実装したい
・ERR_NOSUCHUSERとERR_NOSUCHCHANNEL判断をAfter Checkに実装しなおす

2024-11-01 04:51 UTC, paphio-kitsuki commented on src/event_handler.cpp
> +void EventHandler::CheckChannelTarget(Event& event) {
ちなみにnモードは実装予定ではありません。
課題要件にある最低限実装するモード:
i, k, t, o, l

2024-11-02 23:45 UTC, weijuan82113 commented on src/event_handler.cpp
> +	const std::string& target = event.get_command_params()[0];
該当処理を新しいコード（Joinコマンドの実装）に書き換えた

2024-11-03 01:05 UTC, weijuan82113 commented on src/event_handler.cpp
> +void EventHandler::CheckChannelTarget(Event& event) {
下記テストを実行し、再度コードを修正しました、
確認をお願いします。

## テスト
 -（OK）認証
 -（OK）ERR_NOSUCHNICK
 -（OK）ERR_CANNOTSENDTOCHAN
 -（OK）ERR_NOSUCHCHANNEL
 -（OK）ERR_NOTEXTTOSEND
 -（OK）ユーザー送信確認
 -（OK）チャンネル送信確認

2024-11-03 13:44 UTC, rinonaito reviewed
TOPICのコメントを先に確認してもらった方がわかりやすいと思います。
ご確認願います

2024-11-03 13:44 UTC, rinonaito commented on src/database.cpp
> +			return ;
TOPICでのコメントと同じく、`if (!event.HasErrorOccurred() && event.get_target_num() == 0) `以外の部分は、それぞれPRVMSG専用のメソッド内で判定できると思いましたが、ここでないとダメなのでしょうか？

2024-11-05 07:48 UTC, weijuan82113 commented
既存のコードをマージして下記テストを行いました

## テスト
### 失敗：
- ERR_NEEDMOREPARAMS
```
privmsg nick2
:localhost 461 nick2 PRIVMSG : Not enough parameters.
```
- ERR_NOSUCHNICK
```
privmsg nick3 test
:localhost 401 nick2 PRIVMSG : No such nick
```
- ERR_NOSUCHCHANNEL
```
privmsg #ch2 test
:localhost 403 nick2 PRIVMSG : No such channel
```
- ERR_CANNOTSENDTOCHAN
```
privmsg #ch1 test
:localhost 404 nick2 PRIVMSG : Cannot send to channel
```
- ERR_NOTEXTTOSEND
```
privmsg #ch1 :   
:localhost 412 nick2 PRIVMSG : No text to send
```
### 成功：
#### ユーザー送信
- 第1人称
```
表示しない
```
- 第2人称
```
:nick2!user1@localhost PRIVMSG nick2 :test
```
#### チャンネル送信
- 第1人称
```
privmsg #ch1 test1234
:nick1!user1@localhost PRIVMSG #ch1 :test1234
```
- 第2人称
```
:nick1!user1@localhost PRIVMSG #ch1 :test1234 
```

2024-11-05 15:17 UTC, paphio-kitsuki commented on src/user.cpp
> +		const Channel& channel = dynamic_cast<const ChannelEvent&>(event).get_channel();
重要度・高

2024-11-05 17:49 UTC, weijuan82113 commented on includes/channel.h
> +		const utils::MyVector<const User*>& get_members(void) const;
this->members_でメンバーリストを取得する仕様に変更しました

2024-11-05 17:50 UTC, weijuan82113 commented on includes/event.h
> +		void	ResetErrorStatus();
削除しました

2024-11-05 17:52 UTC, weijuan82113 commented on includes/event.h
> +		int get_target_num(void) const;
こちらはイツキが実装した、IncreaseUserCountとget_user_countでマージする際に対応させてください。

2024-11-05 17:52 UTC, weijuan82113 commented on includes/event.h
> +		int target_num_;
上記と同様にマージ時に修正します

2024-11-05 17:59 UTC, weijuan82113 commented on src/user.cpp
> +		const std::string& rpl_msg = CreateTopicRplMessage(channel, has_topic);
指摘通りに修正しました

2024-11-05 18:02 UTC, weijuan82113 commented
> お疲れさまでした。 すみません。TOPICに関する指摘もこちらに記載してしまいました。

混乱を防ぐために、
PrivmsgブランチはTOPICのコードをマージして、
ここでTOPICの修正も行います。

2024-11-05 18:13 UTC, weijuan82113 commented on src/database.cpp
> +			return ;
もう一度DBを確認するべき役割を明確し、修正しました
```
void Database::CkPrivmsgCommand(Event& event) const {
	const std::vector<std::string> &params = event.get_command_params();

	if (params.size() <  2) {
		event.set_error_status(ErrorStatus::ERR_NEEDMOREPARAMS);
		return;
	}
	if (params[1].empty()) {
		event.set_error_status(ErrorStatus::ERR_NOTEXTTOSEND);
		return;
	}
}
```

2024-11-05 18:15 UTC, weijuan82113 commented on src/event_handler.cpp
> +	const std::string& target = event.get_command_params()[0];
該当関数は使う用途がなくなったので、削除しました。

2024-11-05 18:38 UTC, weijuan82113 commented on src/user.cpp
> +	if (this->joining_channels_.Contains(&channel))
修正を反映しました。

2024-11-05 18:56 UTC, weijuan82113 commented on src/channel.cpp
> +	if (this->mode_map_('t') && SearchByFD(members_, event->get_fd())) {
自分が動作確認した認識は、tモードが設定されるとチャンネルメンバーがチャンネルTOPICを変更できない、tモードが消すとOPERATORとMEMBERとちらでもTOPICを変更できるので、こちらの修正をしませんでした。

2024-11-05 18:59 UTC, paphio-kitsuki commented on src/channel.cpp
> +	if (this->mode_map_('t') && SearchByFD(members_, event->get_fd())) {
この修正でも動作はその通りになるんですけどね。
!= NULLを付けてもらうだけでも大丈夫です。

2024-11-05 19:00 UTC, weijuan82113 commented on src/channel.cpp
> +	if (!member_excuter && !operator_excuter) {
指摘を反映しました

2024-11-05 19:05 UTC, weijuan82113 commented on src/database.cpp
> -		return ;
AfterCheckの後に、下記を追加しました。
とくにここを意図的に削除しませんでした、他のブランチにも削除されたかを注意します。
```
if (event->HasErrorOccurred())
			return ;
```

2024-11-05 19:19 UTC, weijuan82113 commented on src/database.cpp
> +			return ;
指摘通りに、IsChannelEvent条件は次の！IsChannelEventに弾かれreturnするので、こちら不要でした、反映しました。

2024-11-05 19:30 UTC, weijuan82113 commented on src/channel.cpp
> +	if (this->mode_map_('t') && SearchByFD(members_, event->get_fd())) {
ロジック理解しました、指摘通りに修正します。

2024-11-05 20:17 UTC, paphio-kitsuki commented on src/database.cpp
> +			return ;
一番最後に確認しても意味ありません。
AfterCheck関数の前でエラー確認を行ってください。
```suggestion
	if (event->HasErrorOccurred())
			return ;
	this->AfterCheck(*event);
```

2024-11-06 02:33 UTC, weijuan82113 commented on src/database.cpp
> +			return ;
了解です、再度修正し、プシューしました。

2024-11-06 03:34 UTC, weijuan82113 commented
動作確認で、privmsgはparamsを全部送信し切れなかったことを気づき、その修正を行う。
- User::CreateMessage関数のparams表示をUtils::Joinで対応
- GenerateTopicMessage()関数はTopicを初回設定時に表示する関数、こちらもUtils::Joinで対応
  - Utils::Joinはdelimがなくてもeraseするため、find確認を挟むように修正

2024-11-06 03:35 UTC, weijuan82113 commented
> 動作確認で、privmsgはparamsを全部送信し切れなかったことを気づき、その修正を行う。
> 
> * User::CreateMessage関数のparams表示をUtils::Joinで対応
> * GenerateTopicMessage()関数はTopicを初回設定時に表示する関数、こちらもUtils::Joinで対応
>   
>   * Utils::Joinはdelimがなくてもeraseするため、find確認を挟むように修正

2024-11-06 08:13 UTC, paphio-kitsuki commented on includes/utils.h
> +			ret.erase(ret.length() - delim.length());
きちんと動作確認しましたか？
eraseは引数にret.length()が来ても動作は保証されます。
ret.length()が来た時、何もしません。
よって、以前の状態で正しいです。
むしろ、このfindの使用方法は間違っています。findの引数は文字か文字列であり、数値は入りません。
以前の状態に戻してください。
[eraseのリファレンス](https://cpprefjp.github.io/reference/string/basic_string/erase.html)
[findのリファレンス](https://cpprefjp.github.io/reference/string/basic_string/find.html)

```suggestion
		ret.erase(ret.length() - delim.length());
```

以下(以前の状態での)テストコード
```
	std::vector<std::string> vec;
	vec.push_back("a");
	vec.push_back("b");
	vec.push_back("c");
	vec.push_back("d");
	std::cout << utils::Join(vec.begin(), vec.end(), "") << "|" << std::endl;
```
結果
`abcd|`

2024-11-06 09:26 UTC, weijuan82113 commented on includes/utils.h
> +			ret.erase(ret.length() - delim.length());
動作は確認しましたが、動作が不明だったので、もう一度調査

以前の状態でテストをしたところ、TOPIC #ch1 のリプライに下記エラーがでました、
params.size() == 1;
原因はChannel::ExTopicCommand()関数の
this->set_topic(utils::Join(params.begin() + 1, params.end(), " "));ところでした。

utils::Joinで、erase関数にマイナスの値を入れてしまったことが原因でした。
```
ret: ret.size():0
delim:  delim.size():1
ret.erase(ret.length() - delim.length());
```
→再度解消方法を再度見直し、set_topicを行う前にparams.size()>1のことを確認するようにしました。


元々発生したエラー
```
command:TOPIC
command param:
i: 0, size: 4, "#ch1"
vector_length: 2
basic_string::erase: __pos (which is 18446744073709551615) > this->size() (which is 0)
```

2024-11-06 09:55 UTC, paphio-kitsuki commented on includes/utils.h
> +			ret.erase(ret.length() - delim.length());
なるほど、そういうことでしたか。

2024-11-06 10:29 UTC, paphio-kitsuki commented
お疲れさまでした。
良いと思います。
ただ、user_countとtarget_numの都合上、マージはMODEのあとに行ってください。

2024-11-07 08:25 UTC, paphio-kitsuki commented
コンフリクト修正後、コンパイルエラーを修正しました。
軽く動作確認を行い、問題なくメッセージが届くことを確認しました。

2024-11-07 08:25 UTC, merged