44 add quit command
IRC-WIR/ft_irc pull request #86
Opened 2024-10-27 16:44 UTC by rinonaito

Quitコマンドを実装しました。
コマンド入力からの正しい実装はまだしてません、無視する処理も書いていないです。
以下についてみなさんのご意見伺ってから、どちらかに対応します。

本日お話が途中になってしましましたが、コマンド入力からのQUITコマンドに対応するか否かご相談したいです。
対応しなくてもいいかなと思った理由は以下の２点
①課題要件に、コマンドからの入力で接続切断すべきと定められていない
②必須でないにしては変更範囲が大きそう。
　（私が良い方法思いついていないだけかもしれないので、簡単にできそうであれば教えて欲しいです！）
　RFCでQuitコマンドの定義を見ると、Quitメッセージというものが存在します。
　これは、Quitを実行したユーザが所属していたすべてのチャンネルに対して送信されます。
　つまり、複数のチャンネルに所属する全てのユーザに対して送信する必要があります。
　現時点のChannelEventの構造ではChannelを１つ持つようにしていますが、複数持てるように変更しないと
　実現できないのかなと思ってます。

2024-11-02 07:29 UTC, rinonaito commented
QUITしたユーザと同じChannelに所属するユーザへのメッセージ送信機能を追加しました。

2024-11-02 11:52 UTC, paphio-kitsuki requested changes
お疲れさまでした。
申し訳ありませんが、修正を修正していただきたいです。

2024-11-02 11:52 UTC, paphio-kitsuki commented on src/event_handler.cpp
> +				return;
ここは、エラーが発生したので強制QUITする、という場面ですよね？
であれば、checkは不要、、と言いたかったのですが、checkで情報を付加しないと何が起こるかわからなさそうなので、こちらの方(ExecuteCommandを呼び出す)が正しそうですね。
となると、以前の指摘はdatabase_.ExecuteEvent関数を呼び出す場合に沿った指摘だったので、もう一度修正をお願いしたいです。これなら、Eventはnewしたほうが良いです。
```suggestion
				Detach(entry);
				Event* event_ptr = new Event(entry.fd, entry.revents);
				event_ptr->set_command(message::kQuit);
				ExecuteCommand(event_ptr);
				delete event_ptr;
				response_map_.erase(target_fd);
				return;
```

2024-11-02 11:52 UTC, paphio-kitsuki commented on src/event_handler.cpp
>  	{
万が一ですが、見つからなかった場合の対処もすると良いでしょう。
(一気に提案できなかったので分割しています)
その1
```suggestion
	std::vector<struct pollfd>::size_type index = 0;
	for (; index < poll_fd_.size(); index++) {
```

2024-11-02 11:52 UTC, paphio-kitsuki commented on src/event_handler.cpp
>  	poll_fd_.erase(poll_fd_.begin() + target_index);
その2
こちらではもう一点、指摘。
target_fdの取得の仕方ですが、poll_fd_はvectorなので、これで良いです。
何ならこの処理、for文の中に書くともっと短縮できるかも。
```suggestion
		if (poll_fd_[index].fd == entry.fd)
			break ;
	}
	if (index == poll_fd_.size())
		return ;
	int target_fd = poll_fd_[index].fd;
	poll_fd_.erase(poll_fd_.begin() + index);
```

2024-11-02 11:52 UTC, paphio-kitsuki commented on src/event_handler.cpp
> +				Detach(entry);
Detachでentryを消したり、closeしたりするのなら、念のためreturnの直前に行った方が良いかもしれません。

2024-11-02 11:52 UTC, paphio-kitsuki commented on src/event_handler.cpp
> +		return ;
こちらもpollout内で伝えた内容と同様です。

2024-11-02 11:52 UTC, paphio-kitsuki commented on src/event_handler.cpp
> +				Detach(entry);
うーん、、これだけ特別扱いは、、
これまで書いてきたDetachすべて無くして、ExecuteCommand内にまとめたほうが良いかも、、、
悩ましいところですね。

2024-11-02 11:52 UTC, paphio-kitsuki commented on src/user.cpp
> +	if (event.get_executer().get_fd() == this->get_fd()) {
ちょっと複雑になっちゃってますね。自分が実行者かどうかを確かめる際は、
```suggestion
	if (event.get_fd() == this->get_fd()) {
```
で統一しましょう。

2024-11-03 04:15 UTC, rinonaito commented on src/event_handler.cpp
> +				Detach(entry);
確認ありがとう！
①ではなく②ということでしょうか？それともどちらでもない？

①現在のDetachを呼び出す場所を、EventHandler.ExecuteCommandの中へ移動
②現在のDetachをなくし、database側のexQuitとかでDetachできるようにする

2024-11-03 05:09 UTC, paphio-kitsuki commented on src/event_handler.cpp
> +				Detach(entry);
①が望ましいです。

2024-11-03 05:51 UTC, rinonaito commented
修正しました。ご確認願います！

2024-11-03 06:24 UTC, paphio-kitsuki commented on src/event_handler.cpp
>  	}
```suggestion
	for (std::vector<struct pollfd>::iterator it = poll_fd_.begin(); it != poll_fd_.end(); ++it) {
		if (it->fd == fd) {
			close(it->fd);
			poll_fd_.erase(it);
			return ;
		}
	}
```

2024-11-03 06:38 UTC, paphio-kitsuki requested changes
お疲れさまでした。
もう少し、修正お願いします。

2024-11-03 06:38 UTC, paphio-kitsuki commented on src/event_handler.cpp
> +		Detach(entry.fd);
DetachはExecuteCommand内で行うので不要です。
```suggestion
```

2024-11-03 06:38 UTC, paphio-kitsuki commented on src/event_handler.cpp
> +				Detach(entry.fd);
DetachはExecuteCommand内で行うので不要です。
```suggestion
```

2024-11-03 06:38 UTC, paphio-kitsuki commented on src/event_handler.cpp
>  				response_map_.erase(target_fd);
`response_map_.erase(target_fd);`
これもDetach内で行った方が良いと思います。
poll_fd_と連動した方が好ましいので。

2024-11-03 06:38 UTC, paphio-kitsuki commented on src/event_handler.cpp
>  		return ;
このタイミングでDetachは、問題はないのですが、もしQUITコマンドが失敗する可能性があった場合に、想定外の動作をする可能性があるので、最後に行う方が好ましいです。
(下の方が含められなかったので、提案をそのまま受け入れないでください。)
```suggestion
	database_.CheckEvent(event_ptr);
	if (event_ptr->is_do_nothing())
		return ;
	if (EventHandler::CheckNewChannel(*event_ptr))
		this->AddNewChannel(event_ptr);
	AddResponseMap(database_.ExecuteEvent(*event_ptr));
	database_.DeleteFinishedElements();
	if (!event_ptr->HasErrorOccurred() && event_ptr->get_command() == message::kQuit)
		Detach(event_ptr->get_fd());
```

2024-11-03 07:08 UTC, rinonaito commented
みていただきありがとう！気づかないことたくさんで情けない。。修正しました

2024-11-04 11:26 UTC, paphio-kitsuki approved these changes
お疲れさまでした。
良いと思います！
すこし、見やすさについて指摘したので、気に入れば受け入れてください。

2024-11-04 11:26 UTC, paphio-kitsuki commented on src/user.cpp
> +	return OptionalMessage::Empty();
{}でインデントを積みすぎると醜くなるので、避けるべきです。
ここではearly returnしても良いでしょう。
他にも気になる部分に修正を加えています。
```suggestion
	if (event.get_fd() == this->get_fd()) {
		this->is_delete_ = true;
		return OptionalMessage::Empty();
	}
	const User& executer = event.get_executer();
	std::string prefix_message = executer.get_nick_name() + " QUIT : ";
	for (std::vector<const Channel*>::iterator it =
	this->joining_channels_.begin();
	it != this->joining_channels_.end();
	++it) {
		if((*it)->ContainsUser(executer)) {
			std::string context_message;
			if (event.get_event_type() == POLL_HUP)
				context_message = "client dies and EOF occurs on socket";
			else if (event.get_command_params().empty())
				context_message = "client quit";
			else
				context_message = event.get_command_params()[0];
			return OptionalMessage::Create(this->fd_, prefix_message + context_message + "\r\n");
		}
	}
	return OptionalMessage::Empty();
```

2024-11-04 11:32 UTC, merged